iapiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: LoadBalancer
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 3000
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment-rolling-update
  labels:
    app: reactapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
        role: rolling-update
    spec:
      containers:
      - name: sample-reactapp
        image: sampletest19/reactapp-pipeleine:$(BUILD_NUMBER)
        ports:
        - containerPort: 3000
